name: Group Project Workflow
on: push

jobs:
  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Run all tests
        run: mvn verify
        
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v4
        env:
          token: ${{ sectrets.CODECOV_TOKEN }}
          
  build:
    name: Group Project action
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
